### ISSUE TITLE
Performance issues when editing.

### ISSUE THREAD

**Issue by peinwag** [sebhoerl/Twig-netbeans#11]
Has anyone else encountered performance issues when working with the plugin? By issues I mean laggy typing; partially up to 2 seconds for each input while editing a .twig file. But it only seems to be laggy when editing files with lots of twig tags.

Netbeans is running under ubuntu 10.10 with java-6-sun-1.6.0.24.
Edit: same problem on windows 7

**Comment by kwwii** [comment]
I have experienced exactly the same behaviour. Apparently it only happens with longer files.

**Comment by sebhoerl** [comment]
I haven't tested the plugin with long files until now. The lexing seems to be quite slow when there are many tokens. I'll try to find a way to speed things up.

**Comment by beberlei** [comment]
I have the same problem with large files, cant you delay re-lexing by 0.5 seconds after each keystroke?

**Comment by sebhoerl** [comment]
I'm still trying to solve that problem. On the last weekends I tried to hack together some improvements, but now I think that it is not possible to use the current lexer, which is just a rewrite of the PHP version, for huge files. Basically the problem is that the current lexer returns chunks of tokens that must be cached , because Netbeans expects one single token at a time. Nevertheless it is not possible to write such a cache because of the lexing structure. So I think the lexer needs a whole rewrite in order to let Netbeans do it's own effective time management. I have to find some time for this during the next weeks. Just wanted to let you know I'm still there ;)

**Comment by brikou** [comment]
i've noticed this too and it is very difficult to use it this way :(

**Comment by Lightning-Rider** [comment]
Same issue here. Good to know development is under way to fix this.

**Comment by sebhoerl** [comment]
The rewrite is available now in the new repository: https://github.com/blogsh/Twig-for-Netbeans

**Comment by beberlei** [comment]
You should import this code into this repository. You can do the following:
1. Clone this old repo
2. git checkout -bOldImpl
3. git push origin OldImpl
4. git checkout master
5. git rm . (not sure about the flags to remove everything)
6. git commit -m 'Remove old impl.'
7. Copy new code
   8 . git add . 
8. git commit -m 'New impl'
9. git push origin master

Benefit would be that you dont loose the 50 followers for this repository.

**Comment by sebhoerl** [comment]
Thanks, I had not the idea to create a new online branch :)
